#!/usr/bin/env bash
# Generate single_include/disasm64.h from the split sources. STB-style: declarations
# always, definitions under DISASM64_IMPLEMENTATION.
set -e
cd "$(dirname "$0")/.."
out=single_include/disasm64.h
mkdir -p single_include

decls="include/disasm64/types.h include/disasm64/reader.h src/prefix.h src/operand.h src/fmt.h include/disasm64/encode.h include/disasm64/disasm64.h include/disasm64/analysis.h"
impls="src/prefix.cpp src/operand.cpp src/decode.cpp src/format_intel.cpp src/format_att.cpp src/relocate.cpp src/encode.cpp src/analysis.cpp"

{
    echo "// disasm64 - single-header build (generated by tools/amalgamate.sh; edit the split sources)."
    echo "// In exactly ONE translation unit: #define DISASM64_IMPLEMENTATION before including."
    echo "#pragma once"
    for f in $decls; do grep -vE '^#pragma once|^#include "' "$f"; done
    echo "#ifdef DISASM64_IMPLEMENTATION"
    for f in $impls; do grep -vE '^#include "' "$f"; done
    echo "#endif // DISASM64_IMPLEMENTATION"
} > "$out"

echo "wrote $out ($(wc -l < "$out") lines)"
